swagger: "2.0"
info:
  version: 1.0.0
  title: 12factor compatible API
  description: An express js Restful api that follows 12 factor app principles.
  contact:
    email: "polrahul10@gmail.com"
basePath: /v1
tags:
  - name: "Feed"
    description: "Everything about your Posts"

paths:
  /feed/posts:
    get:
      tags:
        - "Feed"
      summary: Gets posts
      description: Returns a list containing all posts
      produces:
        - "application/json"
      parameters: []
      responses:
        200:
          description: A list of posts
          schema:
            $ref: "#/definitions/Posts"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
  /feed/post:
    post:
      tags:
        - "Feed"
      summary: Creates post
      description: Create a new post
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: post
          in: body
          description: The post to create.
          schema:
            $ref: "#/definitions/Post"
      responses:
        201:
          description: Newly created post
          schema:
            properties:
              message:
                type: string
              post:
                $ref: "#/definitions/Post"
        400:
          description: Bad request.
        422:
          $ref: "#/responses/Standard422ErrorResponse"
        500:
          $ref: "#/responses/Standard500ErrorResponse"

definitions:
  User:
    required:
      - name
    properties:
      name:
        type: string
  Post:
    required:
      - _id
    properties:
      _id:
        type: string
      title:
        type: string
      content:
        type: string
      imageUrl:
        type: string
      creator:
        $ref: "#/definitions/User"
      createdAt:
        type: date
  Posts:
    type: array
    items:
      $ref: "#/definitions/Post"
  Error:
    properties:
      code:
        type: string
      message:
        type: string
  ValidationError:
    properties:
      message:
        type: string
      errors:
        type: array
        items:
          type: object

responses:
  Standard500ErrorResponse:
    description: An unexpected error occurred.
    schema:
      $ref: "#/definitions/Error"
  Standard422ErrorResponse:
    description: Validation failed.
    schema:
      $ref: "#/definitions/ValidationError"
